<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Paket extends Model
{
    use HasFactory;
    protected $fillable = [
        'mapel',
        'waktu_pengerjaan',
        'url_gambar',
        'pengaturan',
        'id_user',
        'tanggal_mulai',
        'tanggal_selesai',
    ];

    public function getSoal(){
        return $this->hasMany(Soal::class,'id_paket');
    }

    public function getSoalId(){
        return $this->hasMany(Soal::class,'id_paket','id')->select(['id','id_paket']);
    }

    public function getNilai(){
        return $this->hasMany(Nilai::class, 'id_paket')->orderBy('nilai','DESC')->groupBy('id_siswa')->select(['id_siswa','id_paket'])->selectRaw('sum(nilai) as nilai');
    }

    public function getUser(){
        return $this->belongsTo(User::class, 'id_user');
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleting(
            function ($query) {
                $query->getSoal()->each(function ($soal){
                    $soal->delete();
                });
                $query->getNilai()->each(function ($nilai){
                    $nilai->delete();
                });
            }
        );
    }


}
